### ISSUE TITLE
BP Calculator (LITE)

### ISSUE THREAD

**Issue by joseph-bravo** [joseph-bravo/arks-sanctum#1]
## Goals

- List all augments with BP amount.
- User can select from a list of augments.
- User can view total BP given the selected list of augments.

## Todo

- [ ] HTML skeleton for app
- [ ] Function for creating DOM Tree for single augment checkbox
  - [ ] Loop through augment list with function
- [ ] Listen for input event on checkboxes, update BP number on event.
